# NBA 2022-23' Finals predictions

In [10]:
headers  = {
    'Connection': 'keep-alive',
    'Accept': 'application/json, text/plain, */*',
    'x-nba-stats-token': 'true',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
    'x-nba-stats-origin': 'stats',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Referer': 'https://stats.nba.com/',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
}

In [1]:
from nba_api.stats.static import teams
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.library.parameters import Season
import pandas as pd

In [14]:
# Getting team ID's

nba_teams = teams.get_teams()
team_ids = [team['id'] for team in nba_teams]

teams_pd = pd.DataFrame(nba_teams)
teams_pd

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974
26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988

In [16]:
from nba_api.stats.endpoints import leaguegamelog
season = '2022-23'
team_id1= 1610612748
team_id2= 1610612743

game_log1 = leaguegamelog.LeagueGameLog(team_id_nullable=team_id1, season_nullable=season)
game_log2 = leaguegamelog.LeagueGameLog(tam_id_nullable=team_id2, season_nullable=season)

games1 = game_log1.get_data_frames()[0]
games2 = game_log2.get_data_frames()[0]

TypeError: LeagueGameLog.__init__() got an unexpected keyword argument 'team_id_nullable'

In [12]:
all_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42022,1610612737,ATL,Atlanta Hawks,0042200116,2023-04-27,ATL vs. BOS,L,241,120,...,0.773,12,33,45,28,5,7,10,15,-8.0
1,42022,1610612737,ATL,Atlanta Hawks,0042200115,2023-04-25,ATL @ BOS,W,242,119,...,1.000,6,28,34,26,5,4,8,16,2.0
2,42022,1610612737,ATL,Atlanta Hawks,0042200114,2023-04-23,ATL vs. BOS,L,240,121,...,0.875,11,31,42,25,8,4,12,24,-8.0
3,42022,1610612737,ATL,Atlanta Hawks,0042200113,2023-04-21,ATL vs. BOS,W,240,130,...,0.813,11,37,48,24,5,6,18,15,8.0
4,42022,1610612737,ATL,Atlanta Hawks,0042200112,2023-04-18,ATL @ BOS,L,241,106,...,0.500,19,30,49,21,10,4,15,11,-13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,12022,1610612766,CHA,Charlotte Hornets,0012200054,2022-10-12,CHA @ PHI,L,241,94,...,0.611,8,41,49,21,7,12,23,24,-5.0
83,12022,1610612766,CHA,Charlotte Hornets,0012200043,2022-10-10,CHA vs. WAS,L,239,107,...,0.923,14,30,44,15,5,5,18,20,-9.0
84,12022,1610612766,CHA,Charlotte Hornets,0012200029,2022-10-07,CHA vs. BOS,L,241,103,...,0.682,17,35,52,23,11,8,10,18,-9.0
85,12022,1610612766,CHA,Charlotte Hornets,0012200018,2022-10-05,CHA vs. IND,L,240,97,...,0.611,16,33,49,20,7,4,17,24,-37.2
86,12022,1610612766,CHA,Charlotte Hornets,0012200005,2022-10-02,CHA @ BOS,L,241,93,...,0.643,16,27,43,13,13,2,13,19,-41.0