In [3]:
# Importing the necessary modules. 
import os
import csv
import requests
import time
from bs4 import BeautifulSoup
import pandas as pd

In [5]:
import requests
from bs4 import BeautifulSoup

url_boxscore = 'https://bsnpr.com/juegos/juego?r=BS20221198'
response = requests.get(url_boxscore)
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table in the HTML page
# This page presents the box score
table_boxscore = soup.find_all("table", class_="tabla_stats")[1]
# Home team
table_hometeam = soup.find_all("table", class_="tabla_stats")[2]
# Away team
table_awayteam = soup.find_all("table", class_="tabla_stats")[3]

In [6]:
# Define a list of team numbers and names

teams = [
    (1, 'Cangrejeros', 'Santurce'),
    (2, 'Capitanes', 'Arecibo'),
    (3, 'Atleticos', 'San German'),
    (5, 'Leones', 'Ponce'),
    (6, 'Piratas', 'Quebradillas'),
    (9, 'Vaqueros', 'Bayamon'),
    (10, 'Gigantes', 'Carolina'),
    (12, 'Indios', 'Mayaguez'),
    (14, 'Mets', 'Guaynabo'),
    (15, 'Cariduros', 'Fajardo'),
    (73, 'Grises', 'Humacao'),
    (79, 'Osos', 'Manati')]
# extract the team names and scores from the table_boxscore
team_names = []
team_scores = []
for row in table_boxscore.findAll("tr")[1:]:
    cols = row.findAll("td")
    team_names.append(cols[0].text.strip())
    team_scores.append(cols[-1].text.strip())
    
# Extract the table data
table_data = []
for row in table_boxscore.findAll("tr")[1:]:
    cols = row.findAll("td")[1:-1]
    row_data = [col.text.strip() for col in cols]
    table_data.append(row_data)


# Create a DataFrame from the table data 
df_table = pd.DataFrame(table_data, columns=['1Q', '2Q', '3Q', '4Q'])

# Create a DataFrame for the team names and scores 
df_team = pd.DataFrame({'Team': team_names, 'Score': team_scores})

# Concatenate the two DataFrames
df = pd.concat([df_team, df_table], axis=1)
df

           Team Score  1Q  2Q  3Q  4Q
0       Bayamon    99  19  19  31  30
1  Quebradillas    79  16  17  21  25
2

In [12]:

# Extract the table data fro the home team
table_data_home = []
for row in table_hometeam.findAll("tr")[1:]:
    cols = row.findAll("td")
    row_data = [col.text.strip() for col in cols]
    table_data_home.append(row_data)
    

# Create a DataFrame for the home team stats
df_home = pd.DataFrame(table_data_home, columns=['','Name', 'Min', 'M', 'A', 'FG%', 'M', 'A', '3P%', 'M', 'A', 'FT%', 'O', 'D', 'T', 'AS', 'PF', 'TO', 'ST', 'BS', 'PTS'])

# add a new column team with the value of the data frame earlier
df_home['Team'] = team_names[0]

# Remove the empty column  
#df_home = df_home.drop(columns=['']).iloc[1:]

# add a prefix to the column names of df_home 


# Extract the table data for the away team
table_data_away = []
for row in table_awayteam.findAll("tr")[1:]:
    cols = row.findAll("td")
    row_data = [col.text.strip() for col in cols]
    table_data_away.append(row_data)
    
# Create a DataFrame for teh away team stats
df_away = pd.DataFrame(table_data_away)
df_away['Team'] = team_names[1]


# Remove the empty column
#df_away = df_away.drop(columns=['']).iloc[1:]


print(df_home.index)
print(df_away.index)

# Concat both df 
game_df = pd.concat([df_home, df_away], axis=1)

# 

# Drop the first row
#game_df = game_df.drop(0)

# Reset the index
game_df = game_df.reset_index(drop=True)
print(game_df.index)
game_df

RangeIndex(start=0, stop=15, step=1)
RangeIndex(start=0, stop=13, step=1)
RangeIndex(start=0, stop=15, step=1)

,,Name,Min,M,A,FG%,M,A,3P%,M,...,12,13,14,15,16,17,18,19,20,Team
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,Quebradillas
1,0,"Mojica, Sammy",11:49,0,0,0%,0,1,0%,0,...,0,0,0,0,0,0,0,0,0,Quebradillas
2,1,"Thompson Jr., Stephen",29:20,3,5,60%,4,6,67%,0,...,1,3,4,2,1,1,0,0,12,Quebradillas
3,2,"Gonzalez, Javier",14:46,0,3,0%,1,2,50%,0,...,1,2,3,4,4,2,0,0,0,Quebradillas
4,7,"Duran, Cliff",10:49,0,0,0%,2,2,100%,0,...,1,3,4,1,2,0,3,0,4,Quebradillas
5,8,"Wiley, Jacob",14:54,4,5,80%,0,0,0%,0,...,2,5,7,2,3,6,4,0,18,Quebradillas
6,10,"Doolittle, Kristian",30:46,1,2,50%,4,5,80%,2,...,0,0,0,0,0,0,0,0,7,Quebradillas
7,13,"Rodriguez, Angel Daniel",28:47,3,4,75%,5,5,100%,3,...,1,2,3,2,0,1,0,0,0,Quebradillas
8,18,"Pérez, Owen",3:06,2,3,67%,0,0,0%,0,...,0,0,0,0,0,0,0,0,0,Quebradillas
9,20,"Negron, Alexis J.",3:06,0,0,0%,0,1,0%,0,...,1,0,1,0,1,0,1,0,6,Quebradillas
10,22,"Santiago, Jr., Benito",18:56,1,1,100%,2,6,33%,3,...,1,1,2,6,0,2,1,0,17,Quebradillas
11,28,"Romero, Ismael",21:28,2,4,50%,0,0,0%,3,...,1,1,2,0,2,4,0,0,15,Quebradillas
12,31,"Martinez, Giovanny",2:27,0,0,0%,0,0,0%,0,...,9,17,26,17,13,16,9,0,79,Quebradillas
13,33,"Cuascut, Luis D",9:46,1,1,100%,0,0,0%,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,,Totals:,,17,28,61%,18,28,64%,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# BSN calendar pull 

1. Define a list of team numbers and names:

In [ ]:
# Define a list of team numbers and names

teams = [
    (1, 'Cangrejeros', 'Santurce'),
    (2, 'Capitanes', 'Arecibo'),
    (3, 'Atleticos', 'San German'),
    (5, 'Leones', 'Ponce'),
    (6, 'Piratas', 'Quebradillas'),
    (9, 'Vaqueros', 'Bayamon'),
    (10, 'Gigantes', 'Carolina'),
    (12, 'Indios', 'Mayaguez'),
    (14, 'Mets', 'Guaynabo'),
    (15, 'Cariduros', 'Fajardo'),
    (73, 'Grises', 'Humacao'),
    (79, 'Osos', 'Manati')
]

# Define the range of years, months, and days to scrape
years = range(2021, 2024)
months = range(1, 13)
days = range(1, 100)

# Loop over all possible dates and URLs
for year in years:
    for month in months:
        for day in days:
            # Construct the URL for the current date
            date_str = f"{year}{month:02d}{day:02d}"
            url_boxscore = 'https://bsnpr.com/juegos/juego?r=BS{date_str}'
            
            # Make a request to the current URL and check if it returns a 200 status code
            response = requests.get(url_boxscore)
            if response.status_code == 200:
                print(f'Processing date: {date_str}')
                
                # Parse the HTML content of the page usingg BeautifulSoup
                soup = BeautifulSoup(response.content, 'html.parser')
                
                # Find all divs with class "table tabla_stats"
                tables = soup.find(class_="table tabla_stats")
                # This page presents the box score
                table_boxscore = soup.find_all("table", class_="tabla_stats")[1]
# Home team
                table_hometeam = soup.find_all("table", class_="tabla_stats")[2]
# Away team
                table_awayteam = soup.find_all("table", class_="tabla_stats")[3]



                team_names = []
                team_scores = []
                for row in table_boxscore.findAll("tr")[1:]:
                    cols = row.findAll("td")
                    team_names.append(cols[0].text.strip())
                    team_scores.append(cols[-1].text.strip())
    
# Extract the table data
                table_data = []
                for row in table_boxscore.findAll("tr")[1:]:
                    cols = row.findAll("td")[1:-1]
                    row_data = [col.text.strip() for col in cols]
                    table_data.append(row_data)


# Create a DataFrame from the table data 
                df_table = pd.DataFrame(table_data, columns=['1Q', '2Q', '3Q', '4Q'])

# Create a DataFrame for the team names and scores 
                df_team = pd.DataFrame({'Team': team_names, 'Score': team_scores})

# Concatenate the two DataFrames
                df = pd.concat([df_team, df_table], axis=1)
                
                print(f'Processing Box-Score for the date: {date_str}')
                
                
            
            else: 
                    print(f'No data found for date: {date_str}')

In [ ]:
# Gather the correct libraries 
import os 
import csv 
import requests 
import time
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
# Define the base URL for the boxscores
base_url = 'https://bsnpr.com/juegos/juego?r='

# Define a list of team url number, team name and team town

teams = [
    (1, 'Cangrejeros', 'Santurce'),
    (2, 'Capitanes', 'Arecibo'),
    (3, 'Atleticos', 'San German'),
    (5, 'Leones', 'Ponce'),
    (6, 'Piratas', 'Quebradillas'),
    (9, 'Vaqueros', 'Bayamon'),
    (10, 'Gigantes', 'Carolina'),
    (12, 'Indios', 'Mayaguez'),
    (14, 'Mets', 'Guaynabo'),
    (15, 'Cariduros', 'Fajardo'),
    (73, 'Grises', 'Humacao'),
    (79, 'Osos', 'Manati')
]

# Define the range of years, months, and days to scrape
years = range(2021, 2024)
months = range(1, 13)
days = range(1, 100)

In [ ]:
# Loop over the years, months, and days
for year in years:
    # Create a folder for the year